### ISSUE TITLE
Crashed upon polling for samplers

### ISSUE THREAD

**Issue by JimmyTime** [dinilvalsan/random-pose-generator#1]
This has potential, but it crashed when I polled my instance for sampler types

**Comment by dinilvalsan** [comment]
> This has potential, but it crashed when I polled my instance for sampler types

Hi can you please share link address pasted, are you able to generate image without sampler update?

**Comment by JimmyTime** [comment]
Good question I will try. Here's something I just got by adding some error catching:

requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://127.0.0.1:7860/sdapi/v1/samplers

I am using "http://127.0.0.1:7860/"

**Comment by JimmyTime** [comment]
"Openpose controlnet not detected" - perhaps it's looking down the wrong path(s) in general? for instance I don't know (yet) where exactly my "sdapi/v1/samplers" directory even SHOULD be

**Comment by dinilvalsan** [comment]
Can you please try - - api flag enabled also check if you are running latest automatic1111 and latest pulled control net extension..

**Comment by JimmyTime** [comment]
sure thing, I think you have at least half the answer there with the api flag, which would be my fault :) will let you know

**Comment by JimmyTime** [comment]
Hey I'll close this out, I'm getting images. API did it. I'm still getting some errors, but it runs ```
Error running process: C:\SD\extensions\stable-diffusion-webui-two-shot\scripts\two_shot.py
Traceback (most recent call last):
  File "C:\SD\modules\scripts.py", line 417, in process
    script.process(p, *script_args)
  File "C:\SD\extensions\stable-diffusion-webui-two-shot\scripts\two_shot.py", line 204, in process
    self.filters = self.create_filters_from_ui_params(raw_divisions, raw_positions, raw_weights)
  File "C:\SD\extensions\stable-diffusion-webui-two-shot\scripts\two_shot.py", line 83, in create_filters_from_ui_params
    y, x = position.split(':')
ValueError: not enough values to unpack (expected 2, got 1)

Data shape for DDIM sampling is (1, 4, 78, 117), eta 0
Running DDIM Sampling with 10 timesteps
DDIM Sampler:  70%|█████████████████████████████████████████████████████▏                      | 7/10 [00:22<00:09,  3.18s/it]
Total progress: 17it [01:22,  4.21s/it]`
```
