### ISSUE TITLE
API KO

### ISSUE THREAD

**Issue by XT-404** [dinilvalsan/random-pose-generator#2]
Hello friend, which allows you to generate pauses does not work, I followed the video tutorial and I end up with an invalid API error

http://prime-miller-lexington-subject.trycloudflare.com/

**Comment by dinilvalsan** [comment]
> Hello friend, which allows you to generate pauses does not work, I followed the video tutorial and I end up with an invalid API error
> 
> http://prime-miller-lexington-subject.trycloudflare.com/

@XT-404 the url in the tutorial is my running instance of automatic 1111. You should copy url from your running instance.

If you want how to run automatic 1111 using google colab, checkout this tutorial

https://www.youtube.com/watch?v=axhDQJ1jRn8&ab_channel=AiImagegeneration

Please let me know if you run into further issue
