### ISSUE TITLE
Feature Suggestions

### ISSUE THREAD

**Issue by MrKuenning** [dinilvalsan/random-pose-generator#4]
First of all thanks for making a useful tool for generating batch images for openpose models.
To me this is essential for creating consistent previews for the thousands of open pose files I have collected.
There are a few features I would love to see come to this tool.

- Remember Previous settings
When I open the tool, I have to populate fields that never change such as the endpoint address. It would be nice to have these in a config file.

- Option to not generate Text Files
I don't need to have txt files next to every generated image, it would be nice to have a checkbox to enable this if its wanted.
 
- Output name format
My main use for this tool is to generate a preview of my open pose models, as such I want to have the filename between my model and my result match other than the ending. So that the files will be located next to each other.  Currently I have been using filename.pose.png and filename.preview.jpg.  It would be nice to have input on the output file name, or at least ability to move the word output to the end of the name.
 
- Output file format
In my tens of thousands of AI generated files, I switched to primarily using JPG as it takes up 10x less space. I especially don't need preview files to be large. It would be nice to have the option to save the files as jpg. 

- Ability to just type in a prompt
In version 1 of this tool, I could just type in a prompt to output all of the images to.  Now it seems I need to create a folder and a text file to run a prompt. I think its cool that the tool can have a wildcard like feature.  But it would also be nice if there was just an option to type in a prompt.

Those are just my observations, take it or leave it.  Keep up the good work.  I look forward to trying future iterations.

**Comment by dinilvalsan** [comment]
@MrKuenning thanks for the suggestions! I have incorporated most of it in the current release :)

https://github.com/dinilvalsan/random-pose-generator/releases/tag/v2.0.0

**Comment by MrKuenning** [comment]
Awesome, it's working great!
