### ISSUE TITLE
Feature Request: Name new file from original file name / Don't change original file name.

### ISSUE THREAD

**Issue by MrKuenning** [dinilvalsan/random-pose-generator#5]
Could you make it reference the original name instead of generating a new one?

Example:

If I have a folder with poses titled

```
23-FightingPose.png
25-FightingPose.png
```

If I enter a suffix of _preview it would generate

```
23-FightingPose.png    <--  Unchanged original pose 
23-FightingPose_preview.png   <-- New Generated Image
25-FightingPose.png
25-FightingPose_preview.png
```

Currently, it renames both :

```
00000_mask__preview.png    <--  Original pose 
00000_preview__preview.png    <-- New Generated Image
00000_mask__preview.png
00000_preview__preview.png
```

I lose the original filename/sorting, as well as add the new prefix to the original file.

**Comment by dinilvalsan** [comment]
@MrKuenning can you please try out the updated release here

https://github.com/dinilvalsan/random-pose-generator/releases/tag/v2.0.0

I have not tested with write prompt available

**Comment by MrKuenning** [comment]
That works much better.  Thanks!
